"use client"
import Head from "next/head"
import Snowfall from "react-snowfall"
import { Geist, Geist_Mono } from "next/font/google"
import styles from "@/styles/Home.module.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Snowfall color="#fff4" />
        <main className={styles.main}>
          <h1 style={{ fontSize: "4em" }}>Ciao Gaya!</h1>
          <h2>
            <span style={{ opacity: 0.8, fontWeight: "normal" }}>
              Benvenuta al tuo
            </span>{" "}
            Secret Santa Wrapped 2024 🎄
          </h2>
        </main>
      </div>
    </>
  )
}
